2022-03-06 12:04:20,284 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[elementsInfo]表
2022-03-06 12:04:20,456 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[loginData]表
2022-03-06 12:04:20,456 - config.doExcel - INFO - 创建表[loginData]的数据字典
2022-03-06 12:04:22,275 - common.myUnit - INFO - 打开浏览器
2022-03-06 12:04:22,283 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 12:04:22,639 - pageObject.basePage - INFO - 成功进入http://127.0.0.1:8081/login 
2022-03-06 12:04:22,813 - pageObject.basePage - INFO - http://127.0.0.1:8081/login 加载成功!
2022-03-06 12:04:22,814 - testLogin - INFO -    *** 登录测试用例：loginTest-01 开启密码登陆的教师账号和正确的密码 ***
2022-03-06 12:04:22,921 - pageObject.basePage - INFO - 输入 [admin]
2022-03-06 12:04:23,014 - pageObject.basePage - INFO - 输入 [123456]
2022-03-06 12:04:23,413 - pageObject.basePage - INFO - 点击Sign in
2022-03-06 12:04:25,092 - pageObject.basePage - INFO - 点击教务管理员
2022-03-06 12:04:36,457 - pageObject.basePage - ERROR - 元素定位超时：('xpath', '//*[@id="content"]/div[1]/nav/ul/li[2]/div')
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 61, in findElement
    WebDriverWait(self.driver,10).until(EC.visibility_of_element_located(loc))
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-03-06 12:04:36,566 - testLogin - INFO - 登录测试用例：loginTest-01 未通过！
2022-03-06 12:04:36,566 - testLogin - ERROR - 登录测试用例：%s 成功进入首页，但未成功登录
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\testCase\testLogin.py", line 47, in test_login
    self.login.clickTuichuBtn()
  File "D:\Software\PycharmProjects\sccProjects\pageObject\loginPage.py", line 71, in clickTuichuBtn
    self.click(*self.tuichu)
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 80, in click
    text = self.getVal(*loc)
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 121, in getVal
    element = self.findElement(*loc)
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 64, in findElement
    raise e
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 61, in findElement
    WebDriverWait(self.driver,10).until(EC.visibility_of_element_located(loc))
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-03-06 12:04:37,280 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
2022-03-06 12:04:37,343 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 12:04:39,019 - pageObject.basePage - INFO - 成功进入http://127.0.0.1:8081/login 
2022-03-06 12:04:39,069 - pageObject.basePage - INFO - http://127.0.0.1:8081/login 加载成功!
2022-03-06 12:04:39,070 - testLogin - INFO -    *** 登录测试用例：loginTest-02 开启密码登陆的教师账号和错误的密码 ***
2022-03-06 12:04:49,631 - pageObject.basePage - ERROR - 元素定位超时：('id', 'username')
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 61, in findElement
    WebDriverWait(self.driver,10).until(EC.visibility_of_element_located(loc))
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-03-06 12:04:50,335 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
2022-03-06 12:04:52,461 - common.myUnit - INFO - 退出浏览器
